"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {chromium}=require("playwright"),{createServer}=require("../scripts/preview-server.cjs");
const out=path.resolve(__dirname,"../test-results");fs.mkdirSync(out,{recursive:true});
(async()=>{
  const server=createServer();await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
  const browser=await chromium.launch({headless:true,channel:process.env.HOME_PAGES_TEST_BROWSER||"msedge"});
  const results=[];
  try {
    const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:"reduce"});
    const page=await context.newPage(),errors=[];page.on("pageerror",e=>errors.push(e.message));
    const load=async()=>{await page.goto(`http://127.0.0.1:${server.address().port}/design/`);await page.waitForFunction(()=>!!window.__hpPreview);};
    await load();
    const view=page.locator('.hp-view'),card=page.locator('.hp-card-personal-capture');
    const editor=()=>page.getByRole('dialog',{name:'外观与配色'});
    const open=async()=>{await page.getByRole('button',{name:'自定义',exact:true}).click();await page.getByRole('menuitem',{name:'外观与配色',exact:true}).click();};
    const style=async(el,prop)=>el.evaluate((el,prop)=>getComputedStyle(el).getPropertyValue(prop).trim(),prop);
    const range=async(id,value)=>page.locator('#'+id).evaluate((el,value)=>{el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));},value);
    const preserve=async()=>assert.equal(await page.evaluate(()=>window.savedComposer===document.querySelector('.hp-personal-compose-input')),true,'appearance keeps composer DOM, cursor and undo state');
    await page.locator('.hp-personal-compose-input').fill('配色时保留的演示草稿');
    await page.evaluate(()=>{window.savedComposer=document.querySelector('.hp-personal-compose-input');window.savedComposer.setSelectionRange(2,4);});
    assert.equal(await view.getAttribute('data-hp-material'),'glass');
    assert.match(await style(card,'backdrop-filter'),/blur/);
    await open();await editor().getByRole('combobox',{name:'组件材质',exact:true}).selectOption('solid');await editor().getByRole('button',{name:'保存配色',exact:true}).click();
    assert.equal(await view.getAttribute('data-hp-material'),'solid');await preserve();
    assert.equal(await style(card,'backdrop-filter'),'none');
    await open();await editor().getByRole('combobox',{name:'组件材质',exact:true}).selectOption('glass');await editor().getByRole('button',{name:'保存配色',exact:true}).click();
    const base=await style(view,'background-color');
    await open();
    for(const [name,value] of [['页面背景','#263347'],['卡片底色','#31574a'],['正文与标题','#f2f8f3'],['次要文字','#b9d4c2'],['强调色','#dbbd74'],['边框与高光','#658775'],['输入框底色','#142e28']])await editor().getByLabel(name,{exact:true}).fill(value);
    await range('hp-glass-opacity',80);await range('hp-cardRadius',28);await range('hp-glassBlur',24);
    assert.equal(await style(view,'background-color'),'rgb(38, 51, 71)');
    assert.equal(await style(card,'border-radius'),'28px');assert.match(await style(card,'backdrop-filter'),/blur\(24px\)/);
    assert.match(await style(card,'background-color'),/0\.8/);assert.equal(await style(card,'color'),'rgb(242, 248, 243)');
    assert.equal(await style(page.locator('.hp-personal-compose-input'),'background-color'),'rgb(20, 46, 40)');
    await preserve();assert.equal(await page.evaluate(()=>window.savedComposer.selectionStart),2);
    await editor().getByRole('button',{name:'取消',exact:true}).click();
    assert.equal(await style(view,'background-color'),base);await preserve();
    results.push('live global palette/material/geometry preview and cancellation preserve draft/selection');
    await open();await editor().getByLabel('强调色色值',{exact:true}).fill('#no');
    await editor().getByRole('button',{name:'保存配色',exact:true}).click();
    assert.equal(await editor().count(),1);assert.match(await editor().textContent(),/完整的十六进制/);
    await editor().getByLabel('强调色色值',{exact:true}).fill('#4abf96');
    await range('hp-cardRadius',26);await range('hp-glassBlur',20);await range('hp-glass-opacity',74);
    await editor().getByRole('button',{name:'保存配色',exact:true}).click();await preserve();
    await load();assert.equal(await style(card,'border-radius'),'26px');
    assert.equal(await style(card,'--hp-accent'),'#4abf96');assert.match(await style(card,'background-color'),/0\.74/);
    assert.equal(await page.locator('.hp-personal-compose-input').inputValue(),'配色时保留的演示草稿');
    results.push('validated global colors and material persist on reload');
    await page.evaluate(()=>window.savedComposer=document.querySelector('.hp-personal-compose-input'));
    await open();await editor().getByLabel('强调色',{exact:true}).fill('#ffab33');
    await page.evaluate(()=>window.__hpPreview.vault.failWrites=true);
    await editor().getByRole('button',{name:'保存配色',exact:true}).click();
    assert.match(await editor().textContent(),/模拟布局保存失败/);
    await editor().getByRole('button',{name:'取消',exact:true}).click();
    assert.equal(await style(card,'--hp-accent'),'#4abf96');await preserve();
    await page.evaluate(()=>window.__hpPreview.vault.failWrites=false);
    const widget=()=>page.getByRole('dialog',{name:/配置组件/});
    const openWidget=async()=>{await card.getByRole('button',{name:'配置组件',exact:true}).click();await widget().getByText('外观配色',{exact:true}).click();};
    await openWidget();await widget().getByLabel('组件强调色',{exact:true}).fill('#b09ee8');
    await widget().getByLabel('组件卡片底色',{exact:true}).fill('#29334d');
    await widget().getByLabel('组件文字颜色',{exact:true}).fill('#e5eeff');
    assert.equal(await style(card,'--hp-accent'),'#b09ee8');assert.equal(await style(card,'color'),'rgb(229, 238, 255)');
    assert.equal(await style(page.locator('.hp-card-recent'),'--hp-accent'),'#4abf96');await preserve();
    await widget().getByRole('button',{name:'取消',exact:true}).click();assert.equal(await style(card,'--hp-accent'),'#4abf96');
    await openWidget();await widget().getByLabel('组件强调色',{exact:true}).fill('#b09ee8');
    await widget().getByRole('button',{name:'保存',exact:true}).click();await preserve();
    assert.equal(await style(card,'--hp-accent'),'#b09ee8');
    await load();assert.equal(await style(card,'--hp-accent'),'#b09ee8');
    await page.evaluate(()=>window.savedComposer=document.querySelector('.hp-personal-compose-input'));
    await openWidget();await widget().getByRole('button',{name:'强调色恢复继承',exact:true}).click();
    assert.equal(await style(card,'--hp-accent'),'#4abf96');
    await page.evaluate(()=>window.__hpPreview.vault.failWrites=true);
    await widget().getByRole('button',{name:'保存',exact:true}).click();
    assert.match(await widget().textContent(),/模拟布局保存失败/);
    await widget().getByRole('button',{name:'取消',exact:true}).click();
    assert.equal(await style(card,'--hp-accent'),'#b09ee8');await preserve();
    await page.evaluate(()=>window.__hpPreview.vault.failWrites=false);
    await openWidget();await widget().getByRole('button',{name:'强调色恢复继承',exact:true}).click();
    await widget().getByRole('button',{name:'保存',exact:true}).click();await preserve();
    assert.equal(await style(card,'--hp-accent'),'#4abf96');
    results.push('individual colors preview/cancel/save/reload/inherit and write-failure rollback; no composer rebuild');
    await page.locator('.hp-card-pomodoro').getByRole('button',{name:'配置组件',exact:true}).click();
    await widget().getByText('外观配色',{exact:true}).click();
    await widget().getByLabel('组件强调色',{exact:true}).fill('#aabbcc');
    await page.evaluate(()=>{
      const widget=window.__hpPreview.plugin.getActivePage().widgets.find(item=>item.kind==='pomodoro');
      widget.config={...widget.config,task:'模拟调色期间计时器更新',history:{'2026-01-01':2}};
    });
    await widget().getByRole('button',{name:'保存',exact:true}).click();
    assert.equal(await page.evaluate(()=>window.__hpPreview.plugin.getActivePage().widgets.find(item=>item.kind==='pomodoro').config.task),'模拟调色期间计时器更新');
    results.push('color-only save preserves live timer configuration changed while modal was open');
    await open();await editor().getByRole('button',{name:'恢复默认',exact:true}).click();
    await editor().getByRole('button',{name:'保存配色',exact:true}).click();
    assert.equal(await style(card,'border-radius'),'22px');
    await page.evaluate(()=>document.querySelector('.hp-view').scrollTop=0);
    await page.screenshot({path:path.join(out,'glass-home-dark-1440.png')});
    await open();await editor().getByRole('combobox',{name:'工作台外观',exact:true}).selectOption('light');
    await editor().getByRole('button',{name:'保存配色',exact:true}).click();
    await page.screenshot({path:path.join(out,'glass-home-light-1440.png')});
    await open();await page.screenshot({path:path.join(out,'glass-appearance-editor-1440.png')});
    await editor().getByRole('button',{name:'取消',exact:true}).click();
    for(const width of [375,768]) {
      await page.setViewportSize({width,height:900});await open();
      const geometry=await editor().evaluate(el=>({scroll:el.scrollWidth,client:el.clientWidth,left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right}));
      assert.ok(geometry.scroll<=geometry.client+1 && geometry.left>=0 && geometry.right<=width+1,`${width}px editor fits`);
      await editor().getByLabel('正文与标题色值',{exact:true}).fill('#223344');
      await editor().getByRole('button',{name:'取消',exact:true}).click();
      assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    }
    assert.deepEqual(errors,[]);results.push('responsive color editor fits 375/768px; defaults restored; no runtime errors');
    fs.writeFileSync(path.join(out,'appearance-browser.json'),JSON.stringify(results,null,2));
    console.log(results.map(item=>'PASS '+item).join('\n'));await context.close();
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
