"use strict";
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),{createServer}=require('../scripts/preview-server.cjs');
const out=path.resolve(__dirname,'../test-results');fs.mkdirSync(out,{recursive:true});
(async()=>{
  const server=createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const browser=await chromium.launch({headless:true,channel:'msedge'});
  try {
    const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'});
    const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.address().port}/design/`);await page.waitForFunction(()=>!!window.__hpPreview);
    const modal=()=>page.getByRole('dialog'),button=(name)=>page.getByRole('button',{name,exact:true});
    const tab=(name)=>page.locator('.hp-tabs').getByRole('button',{name,exact:true}).click();
    const customize=async(name)=>{await button('自定义').click();await page.getByRole('menuitem',{name,exact:true}).click();};
    const save=()=>modal().getByRole('button',{name:'保存',exact:true}).click();
    const cancel=()=>modal().getByRole('button',{name:'取消',exact:true}).click();
    const books=()=>page.evaluate(()=>window.__hpPreview.personal.library.list());
    const finance=()=>page.evaluate(()=>window.__hpPreview.personal.finance.load());
    const fits=async()=>{
      const g=await modal().evaluate(el=>({width:el.clientWidth,scroll:el.scrollWidth,left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right,viewport:innerWidth}));
      assert.ok(g.scroll<=g.width+1 && g.left>=0 && g.right<=g.viewport+1,JSON.stringify(g));
    };
    assert.equal(await button('外观配色').count(),0);assert.equal(await button('液态玻璃').count(),0);
    await page.locator('.hp-personal-compose-input').fill('简化界面保留的演示草稿');
    await page.evaluate(()=>window.captureBefore=document.querySelector('.hp-personal-compose-input'));
    await customize('调整布局');assert.ok(await page.locator('.hp-root.is-editing').count());await button('完成编辑').click();
    assert.equal(await page.evaluate(()=>window.captureBefore===document.querySelector('.hp-personal-compose-input')),true);
    await page.locator('.hp-card-personal-capture').getByRole('button',{name:'配置组件',exact:true}).click();
    assert.equal(await modal().getByLabel('组件强调色',{exact:true}).isVisible(),false);
    assert.equal(await modal().getByLabel('宽度（列）',{exact:true}).isVisible(),false);
    assert.equal(await modal().getByLabel('默认记录类型',{exact:true}).isVisible(),true);
    await modal().getByText('外观配色',{exact:true}).press('Enter');
    await modal().getByLabel('组件强调色',{exact:true}).fill('#bbccdd');
    await modal().getByText('外观配色',{exact:true}).click();
    await save();assert.equal(await page.locator('.hp-card-personal-capture').evaluate(el=>el.style.getPropertyValue('--hp-accent')),'#bbccdd');
    await customize('添加组件');
    assert.equal(await modal().getByRole('button',{name:'粘贴代码新建组件',exact:true}).isVisible(),false);
    const catalogCount=await modal().locator('.hp-add-select').count();assert.ok(catalogCount>15);
    await modal().getByLabel('搜索组件',{exact:true}).fill('图书馆');assert.equal(await modal().locator('.hp-add-card:visible').count(),1);
    await modal().getByLabel('搜索组件',{exact:true}).fill('不存在的组件名称');assert.equal(await modal().locator('.hp-add-card:visible').count(),0);
    assert.equal(await modal().getByText('没有匹配的组件，试试其他名称或用途。',{exact:true}).isVisible(),true);
    await modal().getByLabel('搜索组件',{exact:true}).fill('图书馆');
    await modal().locator('.hp-add-select:visible').press('Enter');
    await modal().getByLabel('标题',{exact:true}).waitFor();await cancel();
    assert.equal(await page.locator('.hp-card-personal-library').count(),2);
    await tab('图书馆');await button('添加书籍').click();
    assert.equal(await modal().locator('input:visible,select:visible,textarea:visible').count(),1);
    await modal().getByLabel('书名',{exact:true}).fill('一本先记下来再补充的书');await save();
    let book=(await books()).find(item=>item.title==='一本先记下来再补充的书');assert.ok(book);assert.equal(book.status,'想读');assert.equal(book.current,0);
    await button('书籍资料').click();assert.equal(await modal().getByLabel('作者',{exact:true}).isVisible(),true);
    await modal().getByLabel('作者',{exact:true}).fill('演示作者');await modal().getByLabel('阅读状态',{exact:true}).selectOption('在读');
    await modal().getByLabel('总页数',{exact:true}).fill('160');await save();
    await button('回到书架').click();await button('添加书籍').click();
    await modal().getByLabel('书名',{exact:true}).fill('折叠后仍保存完整资料');await modal().getByText('补充书籍资料（可选）',{exact:true}).click();
    await modal().getByLabel('作者',{exact:true}).fill('资料测试');await modal().getByLabel('阅读状态',{exact:true}).selectOption('已读');
    await modal().getByLabel('总页数',{exact:true}).fill('220');await modal().getByLabel('分类',{exact:true}).fill('文学');
    await modal().getByText('补充书籍资料（可选）',{exact:true}).click();await save();
    book=(await books()).find(item=>item.title==='折叠后仍保存完整资料');assert.equal(book.author,'资料测试');assert.equal(book.status,'已读');assert.equal(book.total,220);assert.equal(book.category,'文学');
    await button('回到书架').click();await button('添加书籍').click();
    await modal().getByLabel('书名',{exact:true}).fill('写入失败可继续');await page.evaluate(()=>window.__hpPreview.vault.failWrites=true);await save();
    await modal().getByRole('alert').filter({hasText:/失败/}).waitFor();assert.equal(await modal().getByLabel('书名',{exact:true}).inputValue(),'写入失败可继续');
    assert.equal(await modal().getByLabel('作者',{exact:true}).isVisible(),true);
    await page.evaluate(()=>window.__hpPreview.vault.failWrites=false);await save();assert.equal((await books()).filter(item=>item.title==='写入失败可继续').length,1);
    await tab('账本');await button('记一笔').click();
    assert.equal(await modal().locator('input:visible,select:visible,textarea:visible').count(),2);
    await modal().getByLabel('金额（元）',{exact:true}).fill('18.50');await modal().getByLabel('分类',{exact:true}).fill('餐饮');await save();
    let state=await finance();assert.equal(state.entries[0].amount,1850);assert.equal(state.entries[0].type,'expense');
    await button('记一笔').click();assert.equal(await modal().getByLabel('分类',{exact:true}).inputValue(),'餐饮');
    await modal().getByLabel('金额（元）',{exact:true}).fill('200');await modal().getByLabel('分类',{exact:true}).fill('收入演示');
    await modal().getByText('日期、收支类型与备注',{exact:true}).click();await modal().getByLabel('收支类型',{exact:true}).selectOption('income');
    await modal().getByLabel('日期',{exact:true}).fill('2026-01-02');await modal().getByLabel('备注（可选）',{exact:true}).fill('完整字段保留');
    await modal().getByText('日期、收支类型与备注',{exact:true}).click();await save();
    const income=(await finance()).entries.find(item=>item.category==='收入演示');assert.equal(income.type,'income');assert.equal(income.date,'2026-01-02');assert.equal(income.note,'完整字段保留');
    await button('添加订阅').click();assert.equal(await modal().locator('input:visible,select:visible,textarea:visible').count(),4);
    await modal().getByLabel('服务名称',{exact:true}).fill('阅读服务');await modal().getByLabel('每期费用（元）',{exact:true}).fill('12');
    await modal().getByLabel('下次到期日',{exact:true}).fill('2026-12-01');await save();
    const sub=(await finance()).subscriptions[0];assert.equal(sub.remindDays,3);assert.equal(sub.active,true);assert.equal(sub.amount,1200);
    await button('添加订阅').click();await modal().getByLabel('服务名称',{exact:true}).fill('校验演示');await modal().getByLabel('每期费用（元）',{exact:true}).fill('9');
    await modal().getByText('提醒与补充信息',{exact:true}).click();await modal().getByLabel('服务网址（可选）',{exact:true}).fill('invalid-url');
    await modal().getByText('提醒与补充信息',{exact:true}).click();await save();
    assert.equal(await modal().getByLabel('服务网址（可选）',{exact:true}).isVisible(),true);assert.equal((await finance()).subscriptions.length,1);await cancel();
    for(const size of [{width:375,height:850},{width:768,height:1000},{width:900,height:375},{width:1440,height:1000}]) {
      await page.setViewportSize(size);await button('记一笔').click();await fits();
      await page.screenshot({path:path.join(out,`simplified-finance-${size.width}.png`)});await cancel();
      await tab('图书馆');
      if(await button('回到书架').count())await button('回到书架').click();
      await button('添加书籍').click();await fits();await page.screenshot({path:path.join(out,`simplified-book-${size.width}.png`)});await cancel();
      await customize('添加组件');await fits();await modal().getByLabel('搜索组件',{exact:true}).fill('阅读');
      await page.screenshot({path:path.join(out,`simplified-catalog-${size.width}.png`)});await modal().press('Escape');
      await tab('账本');
    }
    await tab('工作台');await page.locator('.hp-view').evaluate(el=>el.scrollTop=0);await page.screenshot({path:path.join(out,'simplified-home-1440.png')});
    assert.deepEqual(errors,[]);
    console.log('PASS customization menu, keyboard component search/add, folded widget colors, book title-only/defaults/full edit, hidden field persistence, write failure retry, compact finance/income/subscription forms, invalid hidden field disclosure, and 375/768/900-landscape/1440 layouts.');
    await context.close();
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
